# 改

::: danger 注意！

修改时请注意查询条件！ 否则很容易将全部数据修改

:::

::: tip 提示

当修改数据失败时，`Peewee会引发异常`，通常是 `peewee.IntegrityError` 异常。

`IntegrityError` 异常通常是因为违反了数据库的完整性约束（例如，唯一性约束、外键约束等）而引发的。



以下是一些可能导致插入失败并引发 `IntegrityError` 异常的情况：

1. **唯一性约束冲突**：如果您尝试修改具有唯一性约束的值，而该值已经存在于数据库中，则会引发 `IntegrityError` 异常。
2. **外键约束冲突**：如果您尝试修改具有外键关系的数据，而该外键的关联数据不存在或无效，则会引发 `IntegrityError` 异常。
3. **检查约束失败**：如果修改的数据违反了定义的检查约束条件，也会引发 `IntegrityError` 异常。

:::

## 更新单个对象

::: warning 警告

请确保查询条件能查询到数据

:::

返回：

- 如果用户不存在：`<UserDoesNotExist>` 报错   需要捕捉 `peewee.DoesNotExist` 类型错误

``` python {4-6}
# 通过 id 获取到数据 <Model: User> , 或者通过其他查询方式
# 然后通过 user.name 修改为想要的内容
# 最后 save
user = User.get_by_id(42)
user.name = '刘姥姥'
user.save()

print(user) # id <Model: User>
```







## 单个 / 批量更新

返回：

- 更新的条数 `int`
- 未更改：`0`

``` python {5-6}
from user import User

# 批量更新也是用这种方式
# 将 name==王五 的 age 改为 99
user = User.update(age=99).where(User.name == '王五').execute() # 单个字段
user_many = User.update({'name':'王八犊子','age':18, 'sex':'女'}).where(User.id == 29).execute()  # 多个字段

print(user)  # 更新的条数
print(type(user))  # int
```

